yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('',
         views.index,
         name='index'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    path('signup/', views.SignUp.as_view(), name='signup'),

    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),

    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='reset_confirm'
    ),

    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='reset_complete'
    )

]

yatube/yatube/urls.py
"""yatube URL Configuration"""

from django.conf import settings
from django.conf.urls import handler403, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных -->
<!-- стилей отдельным участкам текста -->
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_body.html
{% load user_filters %}

{% csrf_token %}

{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
      <span class="required text-danger">*</span>
    {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}
      </small>
    {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания -->
<!-- типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" 
        width="30"
        height="30"
        class="d-inline-block align-top"
        alt="">
      <!-- тег span используется для добавления нужных стилей -->
      <!-- отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as name %}
        <li class="nav-item">              
          <a class="nav-link {% if name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if name  == 'about:tech' %}active{% endif %}" 
            href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>      
        {% if user.is_authenticated %}
          <li class="nav-item">              
            <a class="nav-link 
              {% if name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">
              Новая запись
            </a>
          </li> 
          <li class="nav-item">              
            <a class="nav-link link-light
              {% if name  == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}">
              Изменить пароль
            </a>
          </li>                   
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">
              Выйти
            </a>
          </li>
          <li class="nav-item">
            <span class="nav-link link-light
              {% if name == 'posts:profile' %}active{% endif %}">
              Пользователь:
              <a class="link-light" 
                href="{% url 'posts:profile' user.username %}">
                {{ user.username }}
              </a>
            </span>
          </li>
        {% else %}
          <li class="nav-item">              
            <a class="nav-link link-light
              {% if name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">
              Войти
            </a>
          </li>    
          <li class="nav-item">              
            <a class="nav-link link-light
              {% if name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">
              Регистрация
            </a>
          </li>      
        {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/nav_link.html
<li class="nav-item"> 
  <a class="
    nav-link
    {{ color_style }}
    {% if request.resolver_match.view_name == link_name %}active{% endif %}"
    href="{% url link_name %}">{{ link_text }}</a>
</li>

yatube/templates/includes/paginator.html
<!-- Page selector-->
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-3">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">| &lt</a>
        </li>
        <li class="page-item">
          <a class="page-link" 
            href="?page={{ page_obj.previous_page_number }}">
            &lt
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            &gt
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            &gt |
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}
<!-- End page selector-->