yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('',
         views.index,
         name='index'),
]

yatube/yatube/urls.py
"""yatube URL Configuration"""

from django.conf import settings
from django.conf.urls import handler403, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.db.models import Q, F
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Модель группы."""

    title = models.CharField(max_length=200, verbose_name='заголовок')
    slug = models.SlugField(unique=True, verbose_name='идентификатор')
    description = models.TextField(verbose_name='описание')

    class Meta:
        verbose_name = 'группу'  # accusative
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Модель публикации."""

    text = models.TextField(
        verbose_name='текст',
        help_text='введите текст поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='группа',
        help_text='выберите группу'
    )
    image = models.ImageField(
        verbose_name='картинка',
        help_text='выберите графический файл',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        default_related_name = 'posts'
        verbose_name = 'публикацию'  # accusative
        verbose_name_plural = 'публикации'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    """Модель комментария."""

    text = models.TextField(
        verbose_name='текст',
        help_text='введите текст комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='комментируемая публикация'
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата')

    class Meta:
        ordering = ('created',)
        default_related_name = 'comments'
        verbose_name = 'комментарий'  # nominative
        verbose_name_plural = 'комментарии'

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    """Модель учета подписок"""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
        related_name='following'
    )

    class Meta:
        verbose_name = 'подписка'  # nominative
        verbose_name_plural = "подписки"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_subscription'
            ),
            models.CheckConstraint(
                check=~Q(user=F('author')),
                name='no_self_subscriptions'
            )
        ]

    def __str__(self):
        return f'{self.user.username} подписан на {self.author.username}'

yatube/posts/forms.py
from django import forms

from . models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow, User
from .services import get_posts_page


def index(request: HttpRequest):
    """Представление главной страницы."""
    return render(request, 'posts/index.html', {
        'page_obj': get_posts_page(request, Post.objects.all()),
    })


def group_posts(request: HttpRequest, slug: str):
    """Представление группы."""
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': get_posts_page(request, group.posts.all())
    })


def profile(request: HttpRequest, username: str):
    """Представление страницы пользователя."""
    author = get_object_or_404(User, username=username)
    user = request.user
    return render(request, 'posts/profile.html', {
        'author': author,
        'following': (
            user.is_authenticated and user != author
            and Follow.objects.filter(user=user, author=author).exists()
        ),
        'page_obj': get_posts_page(request, author.posts.all())
    })


def post_detail(request: HttpRequest, post_id):
    """Представление для одной публикации."""
    return render(request, 'posts/post_detail.html', {
        'post': get_object_or_404(Post, pk=post_id),
        'form': CommentForm(request.POST)
    })


@login_required
def post_create(request: HttpRequest):
    """Представление для добавления новой публикации."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user  # @login_required
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request: HttpRequest, post_id):
    """Представление для редактирования существующей записи."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
            'is_edit': True
        })
    form.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def add_comment(request: HttpRequest, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post.pk)


@login_required
def follow_index(request: HttpRequest):
    return render(request, 'posts/follow.html', {
        'page_obj': get_posts_page(
            request,
            Post.objects.filter(author__following__user=request.user)
        )
    })


@login_required
def profile_follow(request: HttpRequest, username: str):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect(request.META.get(
        'HTTP_REFERER',
        reverse('posts:profile', args=(username,))
    ))


@login_required
def profile_unfollow(request: HttpRequest, username: str):
    get_object_or_404(
        Follow, user=request.user,
        author__username=username
    ).delete()
    return redirect(request.META.get(
        'HTTP_REFERER',
        reverse('posts:profile', args=(username,))
    ))

yatube/templates/posts/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in post.comments.all %}
  <div class="media mb-4">
    <div class="media-body">
      <p class="mt-0">
        {% with comment.author as author %}
          {% include 'posts/includes/user_name.html' %}
        {% endwith %}
      </p>
        <p>
         {{ comment.text|linebreaksbr }}
        </p>
      </div>
    </div>
{% endfor %} 

yatube/templates/posts/includes/post.html
{% load thumbnail %}
<article class="card">
  <div class="card-header">
    <ul class="list-group">
      {% if not hide_author %}
        <li class="list-group-item border-0  bg-transparent px-0">
          Автор:
          {% include 'posts/includes/user_name.html' with author=post.author %}            
        </li>
      {% endif %}
      <li class="list-group-item border-0  bg-transparent px-0">
        Дата публикации: 
        <a href="{% url 'posts:post_detail' post.pk %}"
          style="text-decoration: none">{{ post.pub_date|date:"d E Y" }}</a>
      </li>
    </ul>
    {% if user == post.author %}
      <!-- эта кнопка видна только автору -->
      <div>
        <a class="btn btn-primary"
        href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
      </div>
    {% endif %}
  </div>
  <div class="card-body">
    {% thumbnail post.image "400x200" crop="center" padding=True upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}"
      >
    {% endthumbnail %}
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    
  </div>
  {% if not hide_group_link and post.group %}
    <div class="card-footer">
      <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}
      </a> 
    </div>
  {% endif %}
</article>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/posts/includes/user_name.html
{% with author.get_full_name as name %}
  {{ name }} {% if name %}({% endif %}
  <a href="{% url 'posts:profile' author.username %}">
    {{ author.username }}
  </a>
  {% if name %}){% endif %} 
{% endwith %}