yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    path('signup/', views.SignUp.as_view(), name='signup'),

    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),

    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='reset_confirm'
    ),

    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='reset_complete'
    )

]

yatube/yatube/urls.py
"""yatube URL Configuration"""

from django.conf import settings
from django.conf.urls import handler403, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        # модель, с которой связана создаваемая форма
        model = User
        # какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends "card_base.html" %}
{% block title %}Вы вышли из системы{% endblock %}
{% block card_header %}Выход{% endblock card_header %}
{% block card_body %}
  Вы вышли из своей учётной записи. Ждём вас снова!
{% endblock card_body %}

yatube/templates/users/login.html
{% extends "card_form.html" %}
{% block title %}Войти{% endblock %}
{% block card_header %}Войти на сайт{% endblock card_header %}
{% block submit %}
  <button type="submit" class="btn btn-primary">
    Войти
  </button>

  <a href="{% url 'users:password_reset' %}" class="btn btn-link">
    Забыли пароль?
  </a> 
{% endblock submit %}

yatube/templates/users/password_change_done.html
{% extends "card_base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block card_header %}Пароль изменён{% endblock card_header %}
{% block card_body %}Пароль изменён успешно{% endblock card_body %}

yatube/templates/users/password_change_form.html
{% extends "card_form.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block card_header %}Изменить пароль{% endblock card_header %}
{% block submit %}
  <button type="submit" class="btn btn-primary">
    Изменить пароль
  </button>
{% endblock submit %}

yatube/templates/users/password_reset_complete.html
{% extends "card_base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block card_header %}
  Восстановление пароля завершено
{% endblock card_header %}
{% block card_body %}
  <p>Ваш пароль был сохранен. Используйте его для входа</p>
  <a href="{% url 'users:login' %}">войти</a>
{% endblock card_body %}

yatube/templates/users/password_reset_confirm.html
{% extends "card_form.html" %}
{% block title %}Сброс пароля{% endblock %}

{% block card_header %}
  {% if validlink %}
    Введите новый пароль
  {% else %}
    Ошибка
  {% endif %}
{% endblock card_header %}

{% block card_body %}
  {% if validlink %}
    {{ block.super }}
  {% else %}
    <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
  {% endif %}
{% endblock card_body %}

{% block submit %}
  <button type="submit" class="btn btn-primary">
    Назначить новый пароль
  </button>
{% endblock submit %}

yatube/templates/users/password_reset_done.html
{% extends "card_base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block card_header %}Отправлено письмо{% endblock card_header %}
{% block card_body %}
  <p>
    Проверьте свою почту, вам должно прийти письмо
    со ссылкой для восстановления пароля.
  </p>
{% endblock card_body %}

yatube/templates/users/password_reset_form.html
{% extends "card_form.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block card_header %}
  Чтобы сбросить старый пароль — введите адрес электронной почты,
  под которым вы регистрировались
{% endblock card_header %}
{% block submit %}
  <button type="submit" class="btn btn-primary">
    Сбросить пароль
  </button>
{% endblock submit %}

yatube/templates/users/signup.html
{% extends "card_form.html" %}
{% block title %}Регистрация{% endblock %}
{% block card_header %}Зарегистрироваться{% endblock card_header %}
{% block submit %}
  <button type="submit" class="btn btn-primary">
    Зарегистрироваться
  </button>
{% endblock submit %}